# Generated by Django 4.0.4 on 2022-05-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='unknown ressource', max_length=30),
        ),
        migrations.AlterField(
            model_name='meal',
            name='minerals',
            field=models.CharField(choices=[('sodium', 'sodium'), ('calcium', 'calcium'), ('potassium', 'potassium'), ('phosphore', 'phosphore'), ('calcaire', 'calcaire')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(default='unknown ressource', max_length=30),
        ),
        migrations.AlterField(
            model_name='meal',
            name='vitamins',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=3, null=True),
        ),
    ]
