# Generated by Django 4.0.4 on 2022-05-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
