# Generated by Django 4.0.4 on 2022-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown food', max_length=30)),
                ('recipe', models.CharField(default='Preparation:\ncooking phase:\n', max_length=2000)),
                ('fat', models.FloatField(default=0)),
                ('proteins', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('water', models.FloatField(default=0)),
                ('vitamins', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=3)),
                ('minerals', models.CharField(choices=[('sodium', 'sodium'), ('calcium', 'calcium'), ('potassium', 'potassium'), ('phosphore', 'phosphore'), ('calcaire', 'calcaire')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='minerals',
            field=models.CharField(choices=[('sodium', 'sodium'), ('calcium', 'calcium'), ('potassium', 'potassium'), ('phosphore', 'phosphore'), ('calcaire', 'calcaire')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='unknown food', max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='proteins',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='unit',
            field=models.CharField(default=' unit(s) of ', max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamins',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='water',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='random menu', max_length=20)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('meals', models.ManyToManyField(to='visitor.meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='visitor.food'),
        ),
        migrations.AddField(
            model_name='meal',
            name='submeals',
            field=models.ManyToManyField(blank=True, to='visitor.meal'),
        ),
    ]
