# Generated by Django 4.0.4 on 2022-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_meal_food_carbohydrates_food_fat_food_fiber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='+', to='visitor.food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='submeals',
            field=models.ManyToManyField(blank=True, related_name='+', to='visitor.meal'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meals',
            field=models.ManyToManyField(related_name='menus', to='visitor.meal'),
        ),
    ]
