# Generated by Django 4.0.4 on 2022-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_food_picture_meal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
