# Generated by Django 4.0.4 on 2022-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_alter_meal_ingredients_alter_meal_submeals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='submeals',
            field=models.ManyToManyField(blank=True, to='visitor.meal'),
        ),
    ]
