# Generated by Django 4.0.4 on 2022-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_alter_meal_submeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='kcal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='kcal',
            field=models.FloatField(default=0),
        ),
    ]
