# Generated by Django 4.0.4 on 2022-05-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_alter_food_picture_alter_meal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
