# Generated by Django 4.0.4 on 2022-05-13 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor', '0005_food_kcal_meal_kcal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True)),
                ('appreciator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealCommenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True)),
                ('appreciator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCommenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='commentors',
            field=models.ManyToManyField(related_name='commentedMeals', through='visitor.MealCommenting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='likers',
            field=models.ManyToManyField(related_name='likedMeals', through='visitor.MealAppreciation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='commentors',
            field=models.ManyToManyField(related_name='commentedMenus', through='visitor.MenuCommenting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='likers',
            field=models.ManyToManyField(related_name='likedMenus', through='visitor.MenuAppreciation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menucommenting',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.menu'),
        ),
        migrations.AddField(
            model_name='menuappreciation',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.menu'),
        ),
        migrations.AddField(
            model_name='mealcommenting',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.meal'),
        ),
        migrations.AddField(
            model_name='mealappreciation',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.meal'),
        ),
    ]
