# Generated by Django 4.0.4 on 2022-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_menu_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minerals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitamins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='minerals',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vitamins',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='minerals',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='vitamins',
        ),
        migrations.AddField(
            model_name='food',
            name='minerals',
            field=models.ManyToManyField(null=True, related_name='+', to='visitor.minerals'),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamins',
            field=models.ManyToManyField(null=True, related_name='+', to='visitor.vitamins'),
        ),
        migrations.AddField(
            model_name='meal',
            name='minerals',
            field=models.ManyToManyField(null=True, related_name='+', to='visitor.minerals'),
        ),
        migrations.AddField(
            model_name='meal',
            name='vitamins',
            field=models.ManyToManyField(null=True, related_name='+', to='visitor.vitamins'),
        ),
    ]
