# Generated by Django 4.0.4 on 2022-05-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_alter_food_minerals_alter_food_vitamins_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vitamins',
            new_name='Mineral',
        ),
        migrations.RenameModel(
            old_name='Minerals',
            new_name='Vitamin',
        ),
    ]
