# Generated by Django 4.0.4 on 2022-05-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_rename_vitamins_mineral_rename_minerals_vitamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='minerals',
            field=models.ManyToManyField(related_name='+', to='visitor.mineral'),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamins',
            field=models.ManyToManyField(related_name='+', to='visitor.vitamin'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='minerals',
            field=models.ManyToManyField(related_name='+', to='visitor.mineral'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='vitamins',
            field=models.ManyToManyField(related_name='+', to='visitor.vitamin'),
        ),
    ]
