# Generated by Django 4.0.4 on 2022-05-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_alter_food_minerals_alter_food_vitamins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(default='unknown description', max_length=300),
        ),
    ]
