# Generated by Django 4.0.4 on 2022-05-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0011_food_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
