# Generated by Django 4.0.4 on 2022-05-28 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor', '0012_alter_mineral_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealappreciation',
            name='appreciator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealAppreciations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menuappreciation',
            name='appreciator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuAppreciations', to=settings.AUTH_USER_MODEL),
        ),
    ]
