# Generated by Django 4.0.4 on 2022-05-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0013_alter_mealappreciation_appreciator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuappreciation',
            old_name='meal',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='menucommenting',
            old_name='meal',
            new_name='menu',
        ),
    ]
